from typing import Optional, List, Union, overload

class DType:
    def __init__(self, name: str): ...
    def __str__(self) -> str: ...

class Device:
    def __init__(self, name: str): ...
    def __str__(self) -> str: ...

class Tensor:
    @staticmethod
    def zeros(shape: List[int], dtype: Optional[DType] = None, device: Optional[Device] = None) -> 'Tensor': ...
    
    @staticmethod
    def rand_uniform(shape: List[int], low: float, high: float, dtype: Optional[DType] = None, device: Optional[Device] = None, requires_grad: bool = False) -> 'Tensor': ...
    
    @staticmethod
    def rand_dropout_mask(shape: List[int], p: float, dtype: Optional[DType] = None, device: Optional[Device] = None) -> 'Tensor': ...
    
    @staticmethod
    def from_list(data: List[float], shape: Optional[List[int]] = None, requires_grad: bool = False, device: Optional[Device] = None) -> 'Tensor': ...
    
    def to(self, device_str: str) -> 'Tensor': ...
    
    @property
    def shape(self) -> List[int]: ...
    
    @property
    def dtype(self) -> DType: ...
    
    @property
    def device(self) -> Device: ...
    
    def to_list(self) -> List[float]: ...
    
    def __add__(self, other: 'Tensor') -> 'Tensor': ...
    def __sub__(self, other: 'Tensor') -> 'Tensor': ...
    def __mul__(self, other: Union['Tensor', float]) -> 'Tensor': ...
    def __matmul__(self, other: 'Tensor') -> 'Tensor': ...
    def __truediv__(self, other: 'Tensor') -> 'Tensor': ...
    def __neg__(self) -> 'Tensor': ...
    
    def transpose(self) -> 'Tensor': ...
    def relu(self) -> 'Tensor': ...
    def sqrt(self) -> 'Tensor': ...
    def sigmoid(self) -> 'Tensor': ...
    def exp(self) -> 'Tensor': ...
    def log(self) -> 'Tensor': ...
    
    def sum(self) -> 'Tensor': ...
    def mean(self) -> 'Tensor': ...
    
    def conv2d(self, weight: 'Tensor', bias: 'Tensor | None' = None, padding: int = 0, stride: int = 1, dilation: int = 1, groups: int = 1) -> 'Tensor': ...
    
    def expand(self, shape: List[int]) -> 'Tensor': ...
    def reshape(self, shape: List[int]) -> 'Tensor': ...
    def sum_to_shape(self, shape: List[int]) -> 'Tensor': ...
    
    @property
    def requires_grad(self) -> bool: ...
    
    def zero_grad(self) -> None: ...
    def backward(self) -> None: ...
    def grad(self) -> Optional['Tensor']: ...
    
    def __repr__(self) -> str: ...
